# Generated by Django 4.0.5 on 2022-11-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='context',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='context',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
