# Generated by Django 4.0.5 on 2022-12-01 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_graph', '0002_alter_context_context_alter_context_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lexical',
            old_name='context1',
            new_name='context',
        ),
        migrations.RemoveField(
            model_name='lexical',
            name='context2',
        ),
        migrations.RemoveField(
            model_name='lexical',
            name='context3',
        ),
    ]
