# Generated by Django 4.0.5 on 2022-12-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_graph', '0003_rename_context1_lexical_context_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lexical',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
