# Generated by Django 4.0.5 on 2022-12-01 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_graph', '0003_rename_context1_lexical_context_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_graph.lexical'),
        ),
    ]
