# Generated by Django 4.0.5 on 2022-12-04 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_graph', '0003_rename_context1_lexical_context_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('exercise_type', models.IntegerField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_graph.lexical')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_graph.context')),
                ('option1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option1', to='knowledge_graph.lexical')),
                ('option2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option2', to='knowledge_graph.lexical')),
                ('option3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option3', to='knowledge_graph.lexical')),
                ('option4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option4', to='knowledge_graph.lexical')),
            ],
        ),
    ]
