# Generated by Django 4.0.5 on 2022-12-06 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_graph', '0004_alter_lexical_weight'),
        ('lesson', '0003_remove_mistake_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='mistake',
            name='context',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='knowledge_graph.context'),
        ),
    ]
