# Generated by Django 4.0.5 on 2022-12-06 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_graph', '0004_alter_lexical_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson', '0004_mistake_context'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learned_Context',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knowledge_graph.context')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
